services:
  app:
    build: .
    depends_on:
      - ds
      - db
    environment:
      - SPRING_LIQUIBASE_ENABLED=true
    ports:
      - "8100:8100"
  ds:
    image: ds:latest
    ports:
      - "8761:8761"
  db:
    image: postgres:14.3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
